### PR TITLE
NEW: Exposes `strand` parameter for `cluster_features_de_novo` (#90)

### PR DESCRIPTION
**Pull request by vaamb**
Can be usefull when working with mixed-orientation sequences in order to merge together sequences with their reverse complement prior to other analyses

Used the same default parameters and description than for the 2 other `cluster_features_*`

### CODE REVIEW

**Comment by lizgehret** [comment]
Apologies for the delayed review on this @vaamb - implementation looks good, but it would be nice to add some associated unit tests to confirm that this added parameter is functioning as expected!

**Comment by lizgehret** [comment]
Hey @vaamb we'll have to bump this to the next release if you aren't able to get unit tests added by EOD tomorrow. Thanks!

**Comment by vaamb** [comment]
@lizgehret I finally found the time to add the tests

**Review by lizgehret — APPROVED** [review]
These tests look good, thanks @vaamb! Will go ahead and get this merged!

**Pull request merged**
