### PR TITLE
MAINT: Add --minseqlength 1

### LINKED ISSUE #69: Missing a length filter cross-reference in `cluster-features-*` actions
**Bug Description**
vsearch apparently applies a minimum length filter of 32 nts to input sequences - our `cluster-features-*` actions appear to assume that no reads are going to be filtered by vsearch, so there is no cross-referencing or post-vsearch filtering applied.

**Steps to reproduce the behavior**
1. Please see reference 1, below.

**Expected behavior**
I see at least two ways to solve, detailed in questions 1 and 2, below.

**Questions**
1. Should we solve by applying post-vsearch filtering? If so, how should we report the filtered sequences back to the user? Is this a new output, or is it lumped in with one of the existing outputs?
2. Should (can?) we solve this by removing the min-length filter on vsearch?

**References**
1. https://forum.qiime2.org/t/error-when-renning-cluster-features-de-novo/14878

### PR DESCRIPTION
**Pull request by Oddant1**
closes #69. All this does right now is add `--minseqlength 1` to the calls to vsearch methods.

Do we need to add new tests for this behavior? Do we need to make any further edits to ensure the behavior we want is actually occuring?

### CODE REVIEW

**Comment by thermokarst** [comment]
Do you know if the DNAFASTAFormat validation allows for records that look like this?

```
> seq1

> seq2

```

**Comment by Oddant1** [comment]
@thermokarst no, files containing empty sequences won't validate as .fasta files. I just tested it to make sure

**Comment by thermokarst** [comment]
Great, thanks for checking. I think we should include a test that fails when run without the `--minlength` additions, but passes once those are present (TDD-style). So, you could write a test that includes sequences less than 32 nts long, which would be filtered out without the minlen flag, but are retained with this new flag. Does that make sense?

**Comment by Oddant1** [comment]
@thermokarst yep that makes sense

**Comment by Oddant1** [comment]
I added tests with length 1 sequences to the Denovo tests and the ClosedReference tests.

**Review by thermokarst — APPROVED** [review]

**Comment by thermokarst** [comment]
Hey @gregcaporaso - just wanted to check in with you briefly on changing this vsearch default parameter - it would be great if you could review this when you get a chance. Thanks!

**Review by gregcaporaso — APPROVED** [review]
I don't see any issues with this change. 

I didn't do a full review here - let me know if you'd like me to do that.

**Pull request merged**
